export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    SAVINGS: '/savings',
    LOANS: '/loans',
    MEMBERSHIP: '/membership',
    CONTACT: '/contact',
    FAQ: '/faq',
    TERMS: '/terms',
    PRIVACY: '/privacy',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_ACCOUNT: '/verify-account',
    VERIFY_OTP: '/verify-otp',
    MFA: '/mfa',
    REGISTRATION_SUCCESS: '/registration-success',
    TERMS: '/terms',
    PRIVACY: '/privacy',
  },
  STAFF: {
    ADMIN_DASHBOARD: '/admin/dashboard',
    MANAGER_DASHBOARD: '/manager/dashboard',
    ACCOUNTANT_DASHBOARD: '/accountant/dashboard',
    AUDITOR_DASHBOARD: '/auditor/dashboard',
    CUSTOMER_SERVICE_DASHBOARD: '/customer-service/dashboard',
    CS_DASHBOARD: '/customer-service/dashboard',
    MEMBERS: '/staff/members',
    RECEIPT_VERIFICATION: '/staff/receipt-verification',
    SAVINGS: '/staff/savings',
    SHARES: '/staff/shares',
    LOANS: '/staff/loans',
    APPROVAL_CENTER: '/staff/approvals',
    TRANSACTIONS: '/staff/transactions',
    ACCOUNTING: '/staff/accounting',
    REPORTS: '/staff/reports',
    FORECASTING: '/staff/forecasting',
    BI_DASHBOARD: '/staff/bi',
    USERS_ROLES: '/staff/users-roles',
    NOTIFICATIONS: '/staff/notifications',
    SUPPORT: '/staff/support',
    AUDIT_LOGS: '/staff/audit-logs',
    MIGRATION: '/staff/migration',
    SETTINGS: '/staff/settings',
  },
  MEMBER: {
    DASHBOARD: '/member/dashboard',
    SAVINGS: '/member/savings',
    SHARES: '/member/shares',
    LOANS: '/member/loans',
    PASSBOOK: '/member/passbook',
    TRANSACTIONS: '/member/transactions',
    NOTIFICATIONS: '/member/notifications',
    SUPPORT: '/member/support',
    PROFILE: '/member/profile',
  }
} as const;
